spring:
  application:
    name: yyok-auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/yyok-admin-v2?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    dbcp2:
      max-idle: 5
      max-wait-millis: 10000
      min-idle: 2
      initial-size: 3
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 18800
    tomcat:
      jdbc-interceptors: ConnectionState;SlowQueryReport(threshold=50)
  redis:
    database: 0
    host: 10.10.3.188
    password:
    timeout: 3000
    jedis:
      pool:
        max-active: 5
        min-idle: 0
        max-wait: 1
        max-idle: 8
    port: 6379
